on: 
  push:
    branches:
      - master
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ” Check secrets
      run: |
        echo "FTP_HOST_IMPOSTOMETRO: ${{ secrets.ftp_host_impostometro }}"
        echo "FTP_USER_IMPOSTOMETRO: ${{ secrets.ftp_user_impostometro }}"
        echo "FTP_PASSWORD_IMPOSTOMETRO: ${{ secrets.ftp_password_impostometro }}"

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_host_impostometro }}
        username: ${{ secrets.ftp_user_impostometro }}
        password: ${{ secrets.ftp_password_impostometro }}
        local-dir: .
        server-dir: htdocs/
